packages:
  - "apps/*"
  - "packages/*"

minimumReleaseAge: 0

hoistWorkspacePackages: false

allowBuilds:
  "@prisma/engines": true
  esbuild: true
  msgpackr-extract: true
  onnxruntime-node: true
  prisma: true
  protobufjs: true
  sharp: true
