/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentDemoRouteImport } from './routes/agent-demo'
import { Route as MermaidDemoRouteImport } from './routes/mermaid-demo'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace.index'
import { Route as WorkspaceProjectsProjectIdRouteImport } from './routes/workspace.projects.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentDemoRoute = AgentDemoRouteImport.update({
  id: '/agent-demo',
  path: '/agent-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const MermaidDemoRoute = MermaidDemoRouteImport.update({
  id: '/mermaid-demo',
  path: '/mermaid-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceProjectsProjectIdRoute =
  WorkspaceProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => WorkspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-demo': typeof AgentDemoRoute
  '/mermaid-demo': typeof MermaidDemoRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/workspace/': typeof WorkspaceIndexRoute
  '/workspace/projects/$projectId': typeof WorkspaceProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-demo': typeof AgentDemoRoute
  '/mermaid-demo': typeof MermaidDemoRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/workspace/projects/$projectId': typeof WorkspaceProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-demo': typeof AgentDemoRoute
  '/mermaid-demo': typeof MermaidDemoRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/workspace/': typeof WorkspaceIndexRoute
  '/workspace/projects/$projectId': typeof WorkspaceProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-demo'
    | '/mermaid-demo'
    | '/workspace'
    | '/workspace/'
    | '/workspace/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-demo'
    | '/mermaid-demo'
    | '/workspace'
    | '/workspace/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/agent-demo'
    | '/mermaid-demo'
    | '/workspace'
    | '/workspace/'
    | '/workspace/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentDemoRoute: typeof AgentDemoRoute
  MermaidDemoRoute: typeof MermaidDemoRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-demo': {
      id: '/agent-demo'
      path: '/agent-demo'
      fullPath: '/agent-demo'
      preLoaderRoute: typeof AgentDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mermaid-demo': {
      id: '/mermaid-demo'
      path: '/mermaid-demo'
      fullPath: '/mermaid-demo'
      preLoaderRoute: typeof MermaidDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/projects/$projectId': {
      id: '/workspace/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/workspace/projects/$projectId'
      preLoaderRoute: typeof WorkspaceProjectsProjectIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  WorkspaceProjectsProjectIdRoute: typeof WorkspaceProjectsProjectIdRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  WorkspaceProjectsProjectIdRoute: WorkspaceProjectsProjectIdRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentDemoRoute: AgentDemoRoute,
  MermaidDemoRoute: MermaidDemoRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
